/*
CREATE DATABASE productos_db;

USE productos_db;

CREATE table productos(
	id_producto INT PRIMERY KEY, 
    descripcion VARCHAR(255),
    ultimo_nro_serie INT DEFAULT 0
)

INSERT INTO productos VALUES
(417, 'SODA ½ LITRO * 12 PET Pack TALCA', 0),
(4900, 'SODA TALCA 2¼ LITRO PET* 6 U. Pack TALCA', 0),
(4910, SIFÓN SODA TALCA 2 LT PET*6U Pack TALCA´´, 0),
(5051, 'TALCA COLA PET ½L DESC *12U Pack TALCA', 0),
(5056, 'TALCA LIMA LIMON PT½L DESC*12U Pack TALCA', 0),
(5066, 'TALCA NARANJA PT ½L DESC*12U Pack TALCA', 0 ),
(5071, 'TALCA POMELO PET ½L DESC *12U Pack TALCA', 0),
(5200, 'TALCA COLA PET 2¼L DESC *6U Pack TALCA', 0), 
(5205, 'TALCA LIMA LIMON PT2¼LDESC*6U Pack TALCA', 0), 
(5215, 'TALCA NARANJA PT 2¼L DESC *6U Pack TALCA', 0),
(5230, 'TALCA POMELO PT 2¼L DESC *6U Pack TALCA', 0),
(5670, 'TALCA COLA PET 3L DESC.*6 U Pack TALCA', 0), 
(5675, 'TALCA LIMA LIMON PET 3L DESC*6 U Pack TALCA', 0), 
(5685, 'TALCA NARANJA 3L DESC *6U Pack TALCA', 0), 
(5690, 'TALCA POMELO PET 3L DESC *6U Pack TALCA', 0), 
(8690, 'VILLA DE MONTAÑA BIDON S/6 G L Bidon VILLA DE MONTAÑA', 0);*/
USE productos_db;
SELECT * FROM productos;











